import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import { SessionProvider } from "next-auth/react"
import { auth } from "@/auth"
import Navbar from "@/components/Navbar";
import HeroSection from "@/components/HeroSection";
import Experiences from "@/components/Experiences";
import Repositories from "@/components/repositories/Repositories-cards";
import Footer from "@/components/Footer";
import React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth();
  return (
      <body>
      <header>
        <Navbar/>
      </header>
      <main className="mainSite flex min-h-screen flex-col bg-midnight-black">

      </main>
      <footer>
        <Footer/>
      </footer>
      </body>
  )
}
